// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxs5A4ATRnvOgrIvUiOi6NJAwb6i1TIic',
    appId: '1:425002886911:android:6fa92e19a02ad1b0698eca',
    messagingSenderId: '425002886911',
    projectId: 'learnxt-88200',
    databaseURL: 'https://learnxt-88200-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learnxt-88200.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNiebYgCg89T-pzniAkq93WamXS51K49A',
    appId: '1:425002886911:web:09c9ffa807ad0358698eca',
    messagingSenderId: '425002886911',
    projectId: 'learnxt-88200',
    authDomain: 'learnxt-88200.firebaseapp.com',
    databaseURL: 'https://learnxt-88200-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learnxt-88200.appspot.com',
    measurementId: 'G-X88PGM7HP2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRpOb2eC-jI8C72ffMnmfWOInJTm6l3AM',
    appId: '1:425002886911:ios:26bdb4debcf9c41e698eca',
    messagingSenderId: '425002886911',
    projectId: 'learnxt-88200',
    databaseURL: 'https://learnxt-88200-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learnxt-88200.appspot.com',
    androidClientId: '425002886911-7rc6t4v8s835a1e0khuncikf55epoojc.apps.googleusercontent.com',
    iosClientId: '425002886911-77t6115qm42upnev8po3pp4qkae9o98d.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnxt',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRpOb2eC-jI8C72ffMnmfWOInJTm6l3AM',
    appId: '1:425002886911:ios:e2463e5bb5d99805698eca',
    messagingSenderId: '425002886911',
    projectId: 'learnxt-88200',
    databaseURL: 'https://learnxt-88200-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learnxt-88200.appspot.com',
    androidClientId: '425002886911-7rc6t4v8s835a1e0khuncikf55epoojc.apps.googleusercontent.com',
    iosClientId: '425002886911-rko1bu3se0tbj3amlvpc908nn5jhkhri.apps.googleusercontent.com',
    iosBundleId: 'com.gurudha.learnxt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNiebYgCg89T-pzniAkq93WamXS51K49A',
    appId: '1:425002886911:web:09c9ffa807ad0358698eca',
    messagingSenderId: '425002886911',
    projectId: 'learnxt-88200',
    authDomain: 'learnxt-88200.firebaseapp.com',
    databaseURL: 'https://learnxt-88200-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learnxt-88200.appspot.com',
    measurementId: 'G-X88PGM7HP2',
  );

}